// Home page config

import { logoListItem } from '@/common/type';

// ======================= logo ==================
const footerLogoList: logoListItem[] = [
  {
    id: 1,
    name: '中国新闻网',
    src: '/images/logo/中国新闻网.png',
    alt: '中国新闻网',
  },
  {
    id: 2,
    name: '光明日报',
    src: '/images/logo/光明日报.png',
    alt: '光明日报',
  },
  {
    id: 3,
    name: '中国经济网',
    src: '/images/logo/中国经济网.png',
    alt: '中国经济网',
  },
  {
    id: 4,
    name: '中央气象台',
    src: '/images/logo/中央气象台.png',
    alt: '中央气象台',
  },
  {
    id: 5,
    name: '人民日报',
    src: '/images/logo/人民日报.png',
    alt: '人民日报',
  },
  {
    id: 6,
    name: '人民网',
    src: '/images/logo/人民网.png',
    alt: '人民网',
  },
  {
    id: 7,
    name: '今日头条',
    src: '/images/logo/今日头条.png',
    alt: '今日头条',
  },
  {
    id: 8,
    name: '凤凰网',
    src: '/images/logo/凤凰网.png',
    alt: '凤凰网',
  },
  {
    id: 9,
    name: '宁夏新闻网',
    src: '/images/logo/宁夏新闻网.png',
    alt: '宁夏新闻网',
  },
  {
    id: 10,
    name: '央视新闻',
    src: '/images/logo/央视新闻.png',
    alt: '央视新闻',
  },
  {
    id: 11,
    name: '微博',
    src: '/images/logo/微博.png',
    alt: '微博',
  },
  {
    id: 12,
    name: '新华网',
    src: '/images/logo/新华网.png',
    alt: '新华网',
  },
  {
    id: 13,
    name: '海外网',
    src: '/images/logo/海外网.png',
    alt: '海外网',
  },
  {
    id: 14,
    name: '环球网',
    src: '/images/logo/环球网.png',
    alt: '环球网',
  },
  {
    id: 15,
    name: '百度地图',
    src: '/images/logo/百度地图.png',
    alt: '百度地图',
  },
  {
    id: 16,
    name: '纽约时报中文网',
    src: '/images/logo/纽约时报中文网.png',
    alt: '纽约时报中文网',
  },
  {
    id: 17,
    name: '网易新闻',
    src: '/images/logo/网易新闻.png',
    alt: '网易新闻',
  },
  {
    id: 18,
    name: '腾讯地图',
    src: '/images/logo/腾讯地图.png',
    alt: '腾讯地图',
  },
  {
    id: 19,
    name: '长沙晚报网',
    src: '/images/logo/长沙晚报网.png',
    alt: '长沙晚报网',
  },
  {
    id: 20,
    name: '闽南网',
    src: '/images/logo/闽南网.png',
    alt: '闽南网',
  },
  {
    id: 21,
    name: '高德地图',
    src: '/images/logo/高德地图.png',
    alt: '高德地图',
  },
  {
    id: 22,
    name: '胶东在线',
    src: '/images/logo/胶东在线.png',
    alt: '胶东在线',
  },
  {
    id: 23,
    name: '资阳网',
    src: '/images/logo/资阳网.png',
    alt: '资阳网',
  },
  {
    id: 24,
    name: '联商网',
    src: '/images/logo/联商网.png',
    alt: '联商网',
  },
  {
    id: 25,
    name: '中国江苏网',
    src: '/images/logo/中国江苏网.png',
    alt: '中国江苏网',
  },
];

// ======================= wordData ====================
const wordData_2010 = [
  {
    name: '给力',
    value: 30,
  },
  {
    name: '淡定',
    value: 29,
  },
  {
    name: '世界杯',
    value: 28,
  },
  {
    name: '世博会',
    value: 27,
  },
  {
    name: '犀利',
    value: 26,
  },
  {
    name: '靠谱',
    value: 25,
  },
  {
    name: '地震',
    value: 24,
  },
  {
    name: '偷菜',
    value: 23,
  },
  {
    name: '任性',
    value: 22,
  },
  {
    name: '悲剧',
    value: 21,
  },
  {
    name: '蒜你狠',
    value: 20,
  },
  {
    name: '微博',
    value: 19,
  },
  {
    name: '浮云',
    value: 18,
  },
  {
    name: '炫父',
    value: 17,
  },
  {
    name: ' Chatroulette',
    value: 1,
  },
  { name: ' iPad', value: 2 },
  { name: ' Justin Bieber', value: 3 },
  { name: ' Nicki Minaj', value: 4 },
  { name: ' Friv', value: 5 },
  { name: ' Myxer', value: 6 },
  { name: ' Katy Perry', value: 7 },
  { name: ' Twitter', value: 8 },
  { name: ' Gamezer', value: 9 },
  { name: 'Facebook', value: 10 },
];
const wordData_2011 = [
  {
    name: 'hold住',
    value: 1,
  },
  {
    name: '乔布斯',
    value: 2,
  },
  {
    name: '地沟油',
    value: 3,
  },
  {
    name: '校车',
    value: 4,
  },
  {
    name: '郭美美',
    value: 5,
  },
  {
    name: '伤不起',
    value: 6,
  },
  {
    name: 'PM2.5',
    value: 7,
  },
  {
    name: '谣盐',
    value: 8,
  },
  {
    name: '占领华尔街',
    value: 9,
  },
  {
    name: '悲剧',
    value: 10,
  },
  { name: ' Fukushima', value: 1 },
  { name: ' iPhone 4s', value: 2 },
  { name: ' Melania Rea', value: 3 },
  { name: ' Salvatore Parolisi', value: 4 },
  { name: ' Lamberto Sposini', value: 5 },
  { name: ' Battlefield 3', value: 6 },
  { name: ' DSK', value: 7 },
  { name: ' iPhone 5', value: 8 },
  { name: ' Gaddafi', value: 9 },
  { name: 'Libya', value: 10 },
];
const wordData_2012 = [
  {
    name: '十八大',
    value: 20,
  },
  {
    name: '钓鱼岛',
    value: 19,
  },
  {
    name: '伦敦奥运',
    value: 18,
  },
  {
    name: '航母style',
    value: 17,
  },
  {
    name: '异地高考',
    value: 16,
  },
  {
    name: '北京暴雨',
    value: 15,
  },
  {
    name: '11·11',
    value: 14,
  },
  {
    name: '逆袭',
    value: 13,
  },
  {
    name: '世界末日',
    value: 12,
  },
  {
    name: '微信',
    value: 11,
  },
  { name: ' Hurricane Sandy', value: 1 },
  { name: ' Kate Middleton Pictures Released', value: 2 },
  { name: ' Olympics 2012', value: 3 },
  { name: ' SOPA Debate', value: 4 },
  { name: ' Costa Concordia crash', value: 5 },
  { name: ' Presidential Debate', value: 6 },
  { name: ' Stratosphere Jump', value: 7 },
  { name: ' Penn State Scandal', value: 8 },
  { name: ' Trayvon Martin shooting', value: 9 },
  { name: 'Pussy Riots', value: 10 },
];
const wordData_2013 = [
  {
    name: '中国梦',
    value: 20,
  },
  {
    name: '土豪',
    value: 19,
  },
  {
    name: '雾霾',
    value: 18,
  },
  {
    name: '中国大妈',
    value: 17,
  },
  {
    name: '单独二孩',
    value: 16,
  },
  {
    name: '比特币',
    value: 15,
  },
  {
    name: '嫦娥三号',
    value: 14,
  },
  {
    name: '房姐',
    value: 13,
  },
  {
    name: '大黄鸭',
    value: 12,
  },
  {
    name: '斯诺登',
    value: 11,
  },
  { name: ' Nelson Mandela', value: 1 },
  { name: ' Paul Walker', value: 2 },
  { name: ' iPhone 5s', value: 3 },
  { name: ' Cory Monteith', value: 4 },
  { name: ' Harlem Shake', value: 5 },
  { name: ' Boston Marathon', value: 6 },
  { name: ' Royal Baby', value: 7 },
  { name: ' Samsung Galaxy S4', value: 8 },
  { name: ' PlayStation 4', value: 9 },
  { name: 'North Korea', value: 10 },
];
const wordData_2014 = [
  {
    name: '依法治国',
    value: 20,
  },
  {
    name: '马航',
    value: 19,
  },
  {
    name: 'APEC蓝',
    value: 18,
  },
  {
    name: '埃博拉',
    value: 17,
  },
  {
    name: '冰桶挑战',
    value: 16,
  },
  {
    name: '监狱风云',
    value: 15,
  },
  {
    name: '克里米亚',
    value: 14,
  },
  {
    name: '《小苹果》',
    value: 13,
  },
  {
    name: '奶茶恋',
    value: 12,
  },
  {
    name: '玉兔号',
    value: 11,
  },
  { name: ' Ebola', value: 1 },
  { name: ' ISIS', value: 2 },
  { name: ' Malaysia Airlines', value: 3 },
  { name: ' Crimea / Ukraine', value: 4 },
  { name: ' Ferguson', value: 5 },
  { name: ' Gaza and Israel', value: 6 },
  { name: ' Scotish Referendum', value: 7 },
  { name: ' Oscar Pistorius trial', value: 8 },
];
const wordData_2015 = [
  {
    name: '抗战胜利70周年阅兵',
    value: 30,
  },
  {
    name: '2022年北京冬奥会',
    value: 29,
  },
  {
    name: '中美互联网论坛',
    value: 28,
  },
  {
    name: '开普勒-452b',
    value: 27,
  },
  {
    name: '屠呦呦',
    value: 26,
  },
  {
    name: '扶老人险',
    value: 25,
  },
  {
    name: '天津爆炸案',
    value: 24,
  },
  {
    name: '第五套人民币',
    value: 23,
  },
  {
    name: '雾霾',
    value: 22,
  },
  {
    name: '全面二孩',
    value: 21,
  },
  { name: ' Charlie Hebdo', value: 1 },
  { name: ' Paris', value: 2 },
  { name: ' Hurricane Patricia', value: 3 },
  { name: ' Isis', value: 4 },
  { name: ' Nepal', value: 5 },
  { name: ' El Chapo', value: 6 },
  { name: ' Greece', value: 7 },
  { name: ' Baltimore Riots', value: 8 },
  { name: ' San Bernardino', value: 9 },
  { name: 'Hurricane Joaquin', value: 10 },
];
const wordData_2016 = [
  {
    name: '里约热内卢奥运会',
    value: 1,
  },
  {
    name: '特朗普',
    value: 2,
  },
  {
    name: '神舟十一号',
    value: 3,
  },
  {
    name: '崔顺实门',
    value: 4,
  },
  {
    name: '人工智能',
    value: 5,
  },
  {
    name: '南海仲裁案',
    value: 6,
  },
  {
    name: '引力波',
    value: 7,
  },
  {
    name: 'G20峰会',
    value: 8,
  },
  {
    name: '蓝瘦香菇',
    value: 9,
  },
  {
    name: '裸条',
    value: 10,
  },
  { name: ' US Election', value: 1 },
  { name: ' Olympics', value: 2 },
  { name: ' Brexit', value: 3 },
  { name: ' Orlando Shooting', value: 4 },
  { name: ' Zika Virus', value: 5 },
  { name: ' Panama Papers', value: 6 },
  { name: ' Nice', value: 7 },
  { name: ' Brussels', value: 8 },
  { name: ' Dallas Shooting', value: 9 },
  { name: 'Kumamoto Earthquake', value: 10 },
];
const wordData_2017 = [
  {
    name: '新时代',
    value: 1,
  },
  {
    name: '共享',
    value: 2,
  },
  {
    name: '雄安新区',
    value: 3,
  },
  {
    name: '金砖国家',
    value: 4,
  },
  {
    name: '人工智能',
    value: 5,
  },
  {
    name: '人类命运共同体',
    value: 6,
  },
  {
    name: '天舟一号',
    value: 7,
  },
  {
    name: '不忘初心',
    value: 8,
  },
  {
    name: '牢记使命',
    value: 9,
  },
  {
    name: '撸起袖子加油干',
    value: 10,
  },
  { name: ' Hurricane Irma', value: 1 },
  { name: ' Bitcoin', value: 2 },
  { name: ' Las Vegas Shooting', value: 3 },
  { name: ' North Korea', value: 4 },
  { name: ' Solar Eclipse', value: 5 },
  { name: ' Hurricane Harvey', value: 6 },
  { name: ' Manchester', value: 7 },
  { name: ' Hurricane Jose', value: 8 },
  { name: ' Hurricane Maria', value: 9 },
  { name: 'April the Giraffe', value: 10 },
];
const wordData_2018 = [
  {
    name: '世界杯',
    value: 20,
  },
  {
    name: '重庆万州公交车坠江',
    value: 10,
  },
  {
    name: '滴滴顺风车事件',
    value: 9,
  },
  {
    name: '改革开放四十周年',
    value: 20,
  },
  {
    name: '高铁霸座',
    value: 15,
  },
  {
    name: '锦鲤',
    value: 16,
  },
  {
    name: '杠精',
    value: 14,
  },
  {
    name: '真香',
    value: 8,
  },
  {
    name: '安排',
    value: 9,
  },
  {
    name: '佛系',
    value: 10,
  },
  { name: 'World Cup', value: 1 },
  { name: ' Hurricane Florence', value: 2 },
  { name: 'Mega Millions Result', value: 3 },
  { name: ' Royal Wedding', value: 4 },
  { name: ' Election Results', value: 5 },
  { name: ' Hurricane Michael', value: 6 },
  { name: ' Kavanaugh Confirmation', value: 7 },
  { name: ' Florida Shooting', value: 8 },
  { name: ' Greve dos caminhoneiros', value: 8 },
  { name: ' Government Shutdown', value: 8 },
];
const wordData_2019 = [
  {
    name: '嫦娥四号',
    value: 1,
  },
  {
    name: '苏炳添',
    value: 2,
  },
  {
    name: '少年的你',
    value: 3,
  },
  {
    name: '我和我的祖国',
    value: 4,
  },
  {
    name: '流浪地球',
    value: 5,
  },
  {
    name: '垃圾分类',
    value: 6,
  },
  {
    name: '网红产品',
    value: 7,
  },
  {
    name: '超前消费',
    value: 8,
  },
  {
    name: '网络短视频',
    value: 9,
  },
  {
    name: '学术造假',
    value: 10,
  },
  {
    name: '英国脱欧',
    value: 11,
  },
  { name: 'Copa America', value: 1 },
  { name: 'Notre Dame', value: 2 },
  { name: 'ICC Cricket World Cup', value: 3 },
  { name: 'Hurricane Dorian', value: 4 },
  { name: 'Rugby World Cup', value: 5 },
  { name: ' Sri Lanka', value: 6 },
  { name: 'Area 51', value: 7 },
  { name: 'India election results', value: 8 },
  { name: '台風 19 号', value: 9 },
  { name: 'Fall of Berlin Wall', value: 10 },
];
const wordData_2020 = [
  {
    name: '中美关系',
    value: 8,
  },
  {
    name: '新冠肺炎病毒',
    value: 30,
  },
  {
    name: '疫情',
    value: 28,
  },
  {
    name: '抗议英雄',
    value: 25,
  },
  {
    name: '钟南山',
    value: 20,
  },
  {
    name: '口罩',
    value: 15,
  },
  {
    name: '火神山',
    value: 10,
  },
  {
    name: '美国大选',
    value: 8,
  },
  {
    name: '隐秘的角落',
    value: 8,
  },
  {
    name: '脱贫攻坚',
    value: 15,
  },
  {
    name: '乘风破浪',
    value: 6,
  },
  {
    name: '凡尔赛',
    value: 6,
  },
  {
    name: '直播带货',
    value: 8,
  },
  {
    name: '网课',
    value: 6,
  },

  {
    name: '民法典',
    value: 5,
  },
  {
    name: '逆行者',
    value: 18,
  },
  {
    name: '武汉',
    value: 20,
  },
  {
    name: '打工人',
    value: 8,
  },
  {
    name: '网抑云',
    value: 6,
  },
  { name: ' Coronavirus', value: 1 },
  { name: 'Election results', value: 2 },
  { name: ' Iran', value: 3 },
  { name: 'Beirut', value: 4 },
  { name: 'Hantavirus', value: 5 },
  { name: 'Stimulus checks', value: 6 },
  { name: 'Unemployment', value: 7 },
  { name: 'Tesla stock', value: 8 },
  { name: ' Bihar election result', value: 9 },
  { name: 'Black Lives Matter', value: 10 },
];
// 默认标签数据
const tagName: string[] = ['文本', '音频', '视频', '图像', '地图', '图表'];
const tagClass: string[] = ['时间', '地点', '人物', '事物', '事件', '现象', '场景'];
const tagNameClass: string[] = [
  '文本',
  '音频',
  '图像',
  '地图',
  '图表',
  '时间',
  '地点',
  '人物',
  '事物',
  '事件',
  '现象',
  '场景',
];

// 国家相关数据
const worldCountries = [
  'Somalia',
  'Liechtenstein',
  'Morocco',
  'W. Sahara',
  'Serbia',
  'Afghanistan',
  'Angola',
  'Albania',
  'Aland',
  'Andorra',
  'United Arab Emirates',
  'Argentina',
  'Armenia',
  'American Samoa',
  'Fr. S. Antarctic Lands',
  'Antigua and Barb.',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Burundi',
  'Belgium',
  'Benin',
  'Burkina Faso',
  'Bangladesh',
  'Bulgaria',
  'Bahrain',
  'Bahamas',
  'Bosnia and Herz.',
  'Belarus',
  'Belize',
  'Bermuda',
  'Bolivia',
  'Brazil',
  'Barbados',
  'Brunei',
  'Bhutan',
  'Botswana',
  'Central African Rep.',
  'Canada',
  'Switzerland',
  'Chile',
  'China',
  "Côte d'Ivoire",
  'Cameroon',
  'Dem. Rep. Congo',
  'Congo',
  'Colombia',
  'Comoros',
  'Cape Verde',
  'Costa Rica',
  'Cuba',
  'Curaçao',
  'Cayman Is.',
  'N. Cyprus',
  'Cyprus',
  'Czech Rep.',
  'Germany',
  'Djibouti',
  'Dominica',
  'Denmark',
  'Dominican Rep.',
  'Algeria',
  'Ecuador',
  'Egypt',
  'Eritrea',
  'Spain',
  'Estonia',
  'Ethiopia',
  'Finland',
  'Fiji',
  'Falkland Is.',
  'France',
  'Faeroe Is.',
  'Micronesia',
  'Gabon',
  'United Kingdom',
  'Georgia',
  'Ghana',
  'Guinea',
  'Gambia',
  'Guinea-Bissau',
  'Eq. Guinea',
  'Greece',
  'Grenada',
  'Greenland',
  'Guatemala',
  'Guam',
  'Guyana',
  'Heard I. and McDonald Is.',
  'Honduras',
  'Croatia',
  'Haiti',
  'Hungary',
  'Indonesia',
  'Isle of Man',
  'India',
  'Br. Indian Ocean Ter.',
  'Ireland',
  'Iran',
  'Iraq',
  'Iceland',
  'Israel',
  'Italy',
  'Jamaica',
  'Jersey',
  'Jordan',
  'Japan',
  'Siachen Glacier',
  'Kazakhstan',
  'Kenya',
  'Kyrgyzstan',
  'Cambodia',
  'Kiribati',
  'Korea',
  'Kuwait',
  'Lao PDR',
  'Lebanon',
  'Liberia',
  'Libya',
  'Saint Lucia',
  'Sri Lanka',
  'Lesotho',
  'Lithuania',
  'Luxembourg',
  'Latvia',
  'Moldova',
  'Madagascar',
  'Mexico',
  'Macedonia',
  'Mali',
  'Malta',
  'Myanmar',
  'Montenegro',
  'Mongolia',
  'N. Mariana Is.',
  'Mozambique',
  'Mauritania',
  'Montserrat',
  'Mauritius',
  'Malawi',
  'Malaysia',
  'Namibia',
  'New Caledonia',
  'Niger',
  'Nigeria',
  'Nicaragua',
  'Niue',
  'Netherlands',
  'Norway',
  'Nepal',
  'New Zealand',
  'Oman',
  'Pakistan',
  'Panama',
  'Peru',
  'Philippines',
  'Palau',
  'Papua New Guinea',
  'Poland',
  'Puerto Rico',
  'Dem. Rep. Korea',
  'Portugal',
  'Paraguay',
  'Palestine',
  'Fr. Polynesia',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saudi Arabia',
  'Sudan',
  'S. Sudan',
  'Senegal',
  'Singapore',
  'S. Geo. and S. Sandw. Is.',
  'Saint Helena',
  'Solomon Is.',
  'Sierra Leone',
  'El Salvador',
  'St. Pierre and Miquelon',
  'São Tomé and Principe',
  'Suriname',
  'Slovakia',
  'Slovenia',
  'Sweden',
  'Swaziland',
  'Seychelles',
  'Syria',
  'Turks and Caicos Is.',
  'Chad',
  'Togo',
  'Thailand',
  'Tajikistan',
  'Turkmenistan',
  'Timor-Leste',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Tanzania',
  'Uganda',
  'Ukraine',
  'Uruguay',
  'United States',
  'Uzbekistan',
  'St. Vin. and Gren.',
  'Venezuela',
  'U.S. Virgin Is.',
  'Vietnam',
  'Vanuatu',
  'Samoa',
  'Yemen',
  'South Africa',
  'Zambia',
  'Zimbabwe',
];
const chinaProvinces = [
  '台湾',
  '河北',
  '山西',
  '内蒙古',
  '辽宁',
  '吉林',
  '黑龙江',
  '江苏',
  '浙江',
  '安徽',
  '福建',
  '江西',
  '山东',
  '河南',
  '湖北',
  '湖南',
  '广东',
  '广西',
  '海南',
  '四川',
  '贵州',
  '云南',
  '西藏',
  '陕西',
  '甘肃',
  '青海',
  '宁夏',
  '新疆',
  '北京',
  '天津',
  '上海',
  '重庆',
  '香港',
  '澳门',
  '南海诸岛',
];

export {
  chinaProvinces,
  footerLogoList,
  tagClass,
  tagName,
  tagNameClass,
  wordData_2010,
  wordData_2011,
  wordData_2012,
  wordData_2013,
  wordData_2014,
  wordData_2015,
  wordData_2016,
  wordData_2017,
  wordData_2018,
  wordData_2019,
  wordData_2020,
  worldCountries,
};
